In [1]:
import pandas as pd

In [5]:
df = pd.read_excel('tickets_complex.xls')

In [4]:
pip install xlrd

Collecting xlrd
  Using cached xlrd-2.0.1-py2.py3-none-any.whl.metadata (3.4 kB)
Using cached xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
Installing collected packages: xlrd
Successfully installed xlrd-2.0.1

[notice] A new release of pip is available: 25.0 -> 25.1.1
[notice] To update, run: /opt/homebrew/Cellar/jupyterlab/4.4.1_1/libexec/bin/python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [8]:
df.sort_values('issue_type').head(15)

,ticket_id,ticket_text,issue_type,urgency_level,product
553,554,Can't log in to my account. Keeps showing capt...,Account Access,Low,ProTab X1
136,137,Can't log in to my account. Keeps showing capt...,Account Access,High,PowerMax Battery
793,794,"Account problem. Assistance needed. Also, I co...",Account Access,Low,FitRun Treadmill
138,139,Can't log in to my account. Keeps showing rese...,Account Access,Medium,ProTab X1
584,585,Can't log in to my account. Keeps showing rese...,Account Access,Medium,UltraClean Vacuum
586,587,Can't log in to my account. Keeps showing capt...,Account Access,Medium,UltraClean Vacuum
281,282,Can't log in to my account. Keeps showing unkn...,Account Access,Low,SmartWatch V2
142,143,Can't log in to my account. Keeps showing erro...,Account Access,Low,RoboChef Blender
144,145,Account problem. Assistance needed.,Account Access,NaN,FitRun Treadmill
795,796,Can't log in to my account. Keeps showing capt...,Account Access,NaN,FitRun Treadmill
276,277,Can't log in to mi account. Keeps showing capt...,Account Access,High,SmartWatch V2
770,771,NaN,Account Access,Medium,PhotoSnap Cam
589,590,Account problem. Assistance needed.,Account Access,High,PowerMax Battery
764,765,Account problem. Assistance needed.,Account Access,High,SmartWatch V2
593,594,Can't log in to mi account. Keeps showing unkn...,Account Access,Low,PhotoSnap Cam

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ticket_id      1000 non-null   int64
 1   ticket_text    945 non-null    object
 2   issue_type     924 non-null    object
 3   urgency_level  948 non-null    object
 4   product        1000 non-null   object
dtypes: int64(1), object(4)
memory usage: 39.2+ KB

In [16]:
df['product'].value_counts()

product
RoboChef Blender     116
Vision LED TV        109
PhotoSnap Cam        103
FitRun Treadmill     102
PowerMax Battery     102
EcoBreeze AC         100
ProTab X1             99
SmartWatch V2         95
SoundWave 300         90
UltraClean Vacuum     84
Name: count, dtype: int64

In [17]:
df['issue_type'].value_counts()

issue_type
Billing Problem       146
General Inquiry       146
Account Access        143
Installation Issue    142
Product Defect        121
Wrong Item            114
Late Delivery         112
Name: count, dtype: int64

In [38]:
dfcsv = pd.read_csv('tickets_complex_cleaned.csv')

In [39]:
dfcsv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ticket_id      1000 non-null   int64
 1   ticket_text    945 non-null    object
 2   issue_type     997 non-null    object
 3   urgency_level  1000 non-null   object
 4   product        1000 non-null   object
dtypes: int64(1), object(4)
memory usage: 39.2+ KB

In [28]:
dfcsv.sort_values('order_id')

,ticket_id,ticket_text,issue_type,urgency_level,product,order_id
327,328,payment issue portal x charged twice 10170,Billing Problem,High,Protab X1,#10170
446,447,ordered ultraclean vacuum got fibrin treadmill...,Wrong Item,High,UltraClean Vacuum,#10191
794,795,payment issue fr mi soundwave 300 refused fr 1...,Billing Problem,High,SoundWave 300,#10237
629,630,10394 3 day late ordered 05 march,NaN,Low,RoboChef Blender,#10394
310,311,payment issue soundwave 300 refused 10599,Billing Problem,High,SoundWave 300,#10599
...,...,...,...,...,...,...
992,993,NaN,Installation Issue,High,SmartWatch V2,NaN
993,994,received wrong product mixed,Wrong Item,High,Protab X1,NaN
994,995,item stock,General Inquiry,High,RoboChef Blender,NaN
997,998,NaN,Installation Issue,Medium,EcoBreeze AC,NaN
999,1000,powermax battery missing stopped working 1 day,Product Defect,Low,PowerMax Battery,NaN

In [36]:
dfcsv['order_id'].dropna().duplicated().value_counts()

order_id
False    361
Name: count, dtype: int64

In [31]:
print(duplicates)

0      False
1      False
2      False
3       True
4      False
       ...
995    False
996    False
997     True
998    False
999     True
Name: order_id, Length: 1000, dtype: bool

In [37]:
duplicates.value_counts()

order_id
True     638
False    362
Name: count, dtype: int64

In [34]:
duplicates.unique()

array([False,  True])